development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URL", "mongodb://localhost:27017/friday_api_dev") %>

production:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URL") %>
